copy \iseproj\5i20\hostmot\indexreg.vhd
copy \iseproj\5i20\hostmot\gcontreg.vhd
copy \iseproj\5i20\hostmot\pwmref.vhd
copy \iseproj\5i20\hostmot\gmodereg.vhd
copy \iseproj\5i20\hostmot\word24rb.vhd
copy \iseproj\5i20\hostmot\wordpr24.vhd
copy \iseproj\5i20\hostmot\threeph.vhd
copy \iseproj\5i20\hostmot\fcounter.vhd
copy \iseproj\5i20\hostmot\timeout.vhd
copy \iseproj\5i20\hostmot\pwmgen.vhd
copy \iseproj\5i20\hostmot\sinetab.xco
copy \iseproj\5i20\hostmot\new3phf.vhd
copy \iseproj\5i20\hostmot\fifomem32.xco
copy \iseproj\5i20\hostmot\fifomem.xco
copy \iseproj\5i20\hostmot\new3phd.vhd
copy \iseproj\5i20\hostmot\hostmot5-4e.vhd
copy \iseproj\5i20\hostmot\countere.vhd
